-- begin PETCLINIC_PET
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_ON_TYPE foreign key (TYPE_ID) references PETCLINIC_PET_TYPE(ID)^
alter table PETCLINIC_PET add constraint FK_PETCLINIC_PET_ON_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID)^
create unique index IDX_PETCLINIC_PET_ID_UNQ on PETCLINIC_PET (IDENTIFICATION_NUMBER, DELETE_TS) ^
create index IDX_PETCLINIC_PET_ON_TYPE on PETCLINIC_PET (TYPE_ID)^
create index IDX_PETCLINIC_PET_ON_OWNER on PETCLINIC_PET (OWNER_ID)^
-- end PETCLINIC_PET
-- begin PETCLINIC_VISIT
alter table PETCLINIC_VISIT add constraint FK_PETCLINIC_VISIT_ON_PET foreign key (PET_ID) references PETCLINIC_PET(ID)^
create index IDX_PETCLINIC_VISIT_ON_PET on PETCLINIC_VISIT (PET_ID)^
-- end PETCLINIC_VISIT
-- begin PETCLINIC_VET_SPECIALTY_LINK
alter table PETCLINIC_VET_SPECIALTY_LINK add constraint FK_VETSPE_ON_VET foreign key (VET_ID) references PETCLINIC_VET(ID)^
alter table PETCLINIC_VET_SPECIALTY_LINK add constraint FK_VETSPE_ON_SPECIALTY foreign key (SPECIALTY_ID) references PETCLINIC_SPECIALTY(ID)^
-- end PETCLINIC_VET_SPECIALTY_LINK
-- begin PETCLINIC_ADDRESS
alter table PETCLINIC_ADDRESS add constraint FK_PETCLINIC_ADDRESS_OWNER foreign key (OWNER_ID) references PETCLINIC_OWNER(ID)^
create index IDX_PETCLINIC_ADDRESS_OWNER on PETCLINIC_ADDRESS (OWNER_ID)^
-- end PETCLINIC_ADDRESS
-- begin PETCLINIC_HEALTH_RECORD
alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_RESPONSIBLE_VET foreign key (RESPONSIBLE_VET_ID) references PETCLINIC_VET(ID)^
alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_PET foreign key (PET_ID) references PETCLINIC_PET(ID)^
alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_VISIT foreign key (VISIT_ID) references PETCLINIC_VISIT(ID)^
create index IDX_PETCLINIC_HEALTH_RECORD_RESPONSIBLE_VET on PETCLINIC_HEALTH_RECORD (RESPONSIBLE_VET_ID)^
create index IDX_PETCLINIC_HEALTH_RECORD_PET on PETCLINIC_HEALTH_RECORD (PET_ID)^
create index IDX_PETCLINIC_HEALTH_RECORD_VISIT on PETCLINIC_HEALTH_RECORD (VISIT_ID)^
-- end PETCLINIC_HEALTH_RECORD
-- begin PETCLINIC_HEALTH_RECORD_ATTACHMENT
alter table PETCLINIC_HEALTH_RECORD_ATTACHMENT add constraint FK_PETCLINIC_HEALTH_RECORD_ATTACHMENT_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table PETCLINIC_HEALTH_RECORD_ATTACHMENT add constraint FK_PETCLINIC_HEALTH_RECORD_ATTACHMENT_HEALTH_RECORD foreign key (HEALTH_RECORD_ID) references PETCLINIC_HEALTH_RECORD(ID)^
create index IDX_PETCLINIC_HEALTH_RECORD_ATTACHMENT_FILE on PETCLINIC_HEALTH_RECORD_ATTACHMENT (FILE_ID)^
create index IDX_PETCLINIC_HEALTH_RECORD_ATTACHMENT_HEALTH_RECORD on PETCLINIC_HEALTH_RECORD_ATTACHMENT (HEALTH_RECORD_ID)^
-- end PETCLINIC_HEALTH_RECORD_ATTACHMENT
-- begin PETCLINIC_EMPLOYEE
alter table PETCLINIC_EMPLOYEE add constraint FK_PETCLINIC_EMPLOYEE_EMPLOYEE_RECORD foreign key (EMPLOYEE_RECORD_ID) references PETCLINIC_EMPLOYEE_RECORD(ID)^
-- end PETCLINIC_EMPLOYEE
-- begin PETCLINIC_VET
alter table PETCLINIC_VET add constraint FK_PETCLINIC_VET_EMPLOYEE foreign key (EMPLOYEE_ID) references PETCLINIC_EMPLOYEE(ID)^
create index IDX_PETCLINIC_VET_EMPLOYEE on PETCLINIC_VET (EMPLOYEE_ID)^
-- end PETCLINIC_VET
