alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_RESPONSIBLE_VET foreign key (RESPONSIBLE_VET_ID) references PETCLINIC_VET(ID);
alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_PET foreign key (PET_ID) references PETCLINIC_PET(ID);
alter table PETCLINIC_HEALTH_RECORD add constraint FK_PETCLINIC_HEALTH_RECORD_VISIT foreign key (VISIT_ID) references PETCLINIC_VISIT(ID);
create index IDX_PETCLINIC_HEALTH_RECORD_RESPONSIBLE_VET on PETCLINIC_HEALTH_RECORD (RESPONSIBLE_VET_ID);
create index IDX_PETCLINIC_HEALTH_RECORD_PET on PETCLINIC_HEALTH_RECORD (PET_ID);
create index IDX_PETCLINIC_HEALTH_RECORD_VISIT on PETCLINIC_HEALTH_RECORD (VISIT_ID);
